var width = 10;
var height = 20;
var area = width * height;
console.log('value of area:', area);
console.log('type of area:', typeof area);
var bill = 100;
var payment = 120;
var change = payment - bill;
console.log('value of change:', change);
console.log('type of change:', typeof change);
var quizzes = 20;
var midterm = 40;
var final = 60;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('type of grade:', typeof grade);
var firstName = 'Mohamed';
var lastName = 'Elmessiry';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('type of fullName', typeof fullName);
var pH = 2;
var isAcidic = pH < 7;
console.log('value of isAcidic', isAcidic);
console.log('type of isAcidic:', typeof isAcidic);
var headCount = 110;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta:', typeof isSparta);
var motto = fullName;
console.log('value of motto:', motto, 'is the GOAT ');
console.log('type of motto:', typeof motto);
